apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: ecommerce-dev
type: Opaque
stringData:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_USER: admin
  DB_PASS: secret
  DB_NAME: ecommerce
  JWT_SECRET: super_secret_key
  JWT_EXPIRES_IN: 1d
